# Generated by Django 6.0.7 on 2026-08-18 11:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=20)),
                ('referred_type', models.CharField(blank=True, choices=[('RENT', 'Rent Customer'), ('PURCHASE', 'Purchase Customer')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUALIFIED', 'Qualified'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING', max_length=12)),
                ('qualifying_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_record', to='customers.customer')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('APP_WELCOME', 'App Welcome Reward'), ('RENT_REFERRAL', 'Rent to Rent Referral'), ('RENT_TO_PURCHASE', 'Rent to Purchase Referral'), ('PURCHASE_TO_RENT', 'Purchase to Rent Referral'), ('PURCHASE_REFERRAL', 'Purchase to Purchase Referral')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_bill_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('usage_categories', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PARTIAL', 'Partially Used'), ('USED', 'Fully Used'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed'), ('HOLD', 'On Hold')], default='ACTIVE', max_length=12)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_rewards', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='referrals.referral')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('REVERSAL', 'Reversal'), ('EXPIRY', 'Expiry'), ('ADJUSTMENT', 'Adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(blank=True, default='', max_length=40)),
                ('reference_id', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='referrals.walletreward')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('referrer', 'referred_user'), name='unique_referrer_referred_user'),
        ),
    ]
