# Generated by Django 6.0.7 on 2026-07-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_romodelpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('INSTALLED', 'Installed'), ('SERVICE', 'Service'), ('REPAIR', 'Repair'), ('RETURNED', 'Returned'), ('REFURBISHED', 'Refurbished'), ('SCRAP', 'Scrap')], default='WAREHOUSE', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ro_assets', to='customers.customer')),
                ('ro_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='products.romodel')),
            ],
        ),
    ]
