# Generated by Django 6.0.7 on 2026-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roasset',
            name='status',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('ASSIGNED', 'Assigned'), ('INSTALLED', 'Installed'), ('SERVICE', 'Service'), ('REPAIR', 'Repair'), ('RETURNED', 'Returned'), ('REFURBISHED', 'Refurbished'), ('SCRAP', 'Scrap')], default='WAREHOUSE', max_length=20),
        ),
    ]
