name: ari_smart_ro_app
description: "ARI SMART RO Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  http: ^1.5.0
  http_parser: ^4.1.2
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5
  mobile_scanner: ^5.2.3
  signature: ^5.5.0
  path_provider: ^2.1.5
  google_maps_flutter: ^2.12.3
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  video_player: ^2.14.0
  google_mlkit_face_detection: ^0.14.0
  record: ^6.1.2
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/ari_smart_ro_icon.png
    - assets/images/ari_launcher_icon.png
    - assets/videos/ari_water_fill.mp4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/ari_launcher_icon.png"
  min_sdk_android: 21
