from django.urls import path

from .device_health import EmployeeDeviceHealthAPIView, AdminDeviceHealthAPIView
from .views import (
    UpdateLiveLocationAPIView,
    EngineerLiveMapAPIView,
    EmployeeProfileAPIView,
    EngineerListAPIView,
    AssignmentEmployeeListAPIView,
    FaceEnrollmentAPIView,
    AdminFaceEnrollmentControlAPIView,
    AdminFaceEnrollmentListAPIView,
    EmployeeManagementAPIView,
    EmployeeCustomerEditPermissionAPIView,
    EmployeeLifecycleAPIView,
    EmployeeCareerMovementAPIView,
    EmployeeCareerMovementActionAPIView,
    EmployeeIdCardAPIView,
    EmployeeIdVerifyAPIView,
)
from .hrms import EmployeeDocumentComplianceAPIView, EmployeeHrmsDashboardAPIView, EmployeePenaltyActionAPIView, EmployeePenaltyAPIView, HolidayAPIView, HolidayDetailAPIView, LeaveRequestAPIView, LeaveReviewAPIView, PayrollActionAPIView, PayrollAPIView, PayrollExcelReportAPIView, PerformanceReviewActionAPIView, PerformanceReviewAPIView
from .training import (
    TrainingDetailAPIView,
    TrainingLessonCompleteAPIView,
    TrainingListAPIView,
    TrainingQuizSubmitAPIView,
    TrainingTrainerReviewAPIView,
    TrainingCertificateIssueAPIView,
    TrainingCertificateRevokeAPIView,
    TrainingCertificateVerifyAPIView,
    TrainingCertificatePDFAPIView,
    AdminTrainingCourseAPIView,
    AdminTrainingCourseDetailAPIView,
    AdminTrainingLessonAPIView,
    AdminTrainingLessonDetailAPIView,
    AdminTrainingQuestionAPIView,
    AdminTrainingQuestionDetailAPIView,
    AdminTrainingAssignAPIView,
)

urlpatterns = [
    path("employees/device-health/", EmployeeDeviceHealthAPIView.as_view(), name="employee-device-health"),
    path("employees/admin/device-health/", AdminDeviceHealthAPIView.as_view(), name="admin-device-health"),
    path("employees/manage/", EmployeeManagementAPIView.as_view(), name="employee-management"),
    path(
        "employees/manage/<int:employee_id>/customer-edit-permission/",
        EmployeeCustomerEditPermissionAPIView.as_view(),
        name="employee-customer-edit-permission",
    ),
    path("employees/id-card/", EmployeeIdCardAPIView.as_view(), name="employee-id-card"),
    path("employees/verify-id/<str:code>/", EmployeeIdVerifyAPIView.as_view(), name="employee-id-verify"),
    path(
        "employees/manage/<int:employee_id>/lifecycle/",
        EmployeeLifecycleAPIView.as_view(),
        name="employee-lifecycle",
    ),
    path(
        "employees/manage/<int:employee_id>/career/",
        EmployeeCareerMovementAPIView.as_view(),
        name="employee-career-movements",
    ),
    path(
        "employees/manage/<int:employee_id>/career/<int:movement_id>/action/",
        EmployeeCareerMovementActionAPIView.as_view(),
        name="employee-career-movement-action",
    ),
    path("employees/hrms/dashboard/", EmployeeHrmsDashboardAPIView.as_view(), name="hrms-dashboard"),
    path("employees/hrms/holidays/", HolidayAPIView.as_view(), name="hrms-holidays"),
    path("employees/hrms/holidays/<int:holiday_id>/", HolidayDetailAPIView.as_view(), name="hrms-holiday-detail"),
    path("employees/hrms/leaves/", LeaveRequestAPIView.as_view(), name="hrms-leaves"),
    path("employees/hrms/leaves/<int:leave_id>/review/", LeaveReviewAPIView.as_view(), name="hrms-leave-review"),
    path("employees/hrms/payroll/", PayrollAPIView.as_view(), name="hrms-payroll"),
    path("employees/hrms/payroll/<int:payroll_id>/action/", PayrollActionAPIView.as_view(), name="hrms-payroll-action"),
    path("employees/hrms/penalties/", EmployeePenaltyAPIView.as_view(), name="hrms-penalties"),
    path("employees/hrms/penalties/<int:penalty_id>/action/", EmployeePenaltyActionAPIView.as_view(), name="hrms-penalty-action"),
    path("employees/hrms/performance/", PerformanceReviewAPIView.as_view(), name="hrms-performance"),
    path("employees/hrms/performance/<int:review_id>/action/", PerformanceReviewActionAPIView.as_view(), name="hrms-performance-action"),
    path("employees/hrms/documents/", EmployeeDocumentComplianceAPIView.as_view(), name="hrms-documents"),
    path("employees/hrms/training/", TrainingListAPIView.as_view(), name="hrms-training"),
    path("employees/hrms/training/admin/courses/", AdminTrainingCourseAPIView.as_view(), name="hrms-training-admin-courses"),
    path("employees/hrms/training/admin/courses/<int:course_id>/", AdminTrainingCourseDetailAPIView.as_view(), name="hrms-training-admin-course-detail"),
    path("employees/hrms/training/admin/courses/<int:course_id>/lessons/", AdminTrainingLessonAPIView.as_view(), name="hrms-training-admin-lessons"),
    path("employees/hrms/training/admin/courses/<int:course_id>/lessons/<int:lesson_id>/", AdminTrainingLessonDetailAPIView.as_view(), name="hrms-training-admin-lesson-detail"),
    path("employees/hrms/training/admin/courses/<int:course_id>/questions/", AdminTrainingQuestionAPIView.as_view(), name="hrms-training-admin-questions"),
    path("employees/hrms/training/admin/courses/<int:course_id>/questions/<int:question_id>/", AdminTrainingQuestionDetailAPIView.as_view(), name="hrms-training-admin-question-detail"),
    path("employees/hrms/training/admin/courses/<int:course_id>/assign/", AdminTrainingAssignAPIView.as_view(), name="hrms-training-admin-assign"),
    path("employees/hrms/training/<int:assignment_id>/", TrainingDetailAPIView.as_view(), name="hrms-training-detail"),
    path("employees/hrms/training/<int:assignment_id>/lessons/<int:lesson_id>/complete/", TrainingLessonCompleteAPIView.as_view(), name="hrms-training-lesson-complete"),
    path("employees/hrms/training/<int:assignment_id>/quiz/", TrainingQuizSubmitAPIView.as_view(), name="hrms-training-quiz"),
    path("employees/hrms/training/<int:assignment_id>/lessons/<int:lesson_id>/trainer-review/", TrainingTrainerReviewAPIView.as_view(), name="hrms-training-trainer-review"),
    path("employees/hrms/training/<int:assignment_id>/certificate/issue/", TrainingCertificateIssueAPIView.as_view(), name="hrms-training-certificate-issue"),
    path("employees/hrms/training/<int:assignment_id>/certificate/revoke/", TrainingCertificateRevokeAPIView.as_view(), name="hrms-training-certificate-revoke"),
    path("employees/hrms/training/certificates/verify/<str:code>/", TrainingCertificateVerifyAPIView.as_view(), name="hrms-training-certificate-verify"),
    path("employees/hrms/training/certificates/<str:code>/pdf/", TrainingCertificatePDFAPIView.as_view(), name="hrms-training-certificate-pdf"),
    path("employees/hrms/reports/payroll.xlsx", PayrollExcelReportAPIView.as_view(), name="hrms-payroll-excel"),
    path(
        "employees/live-location/",
        UpdateLiveLocationAPIView.as_view(),
        name="live-location",
    ),
    path(
        "employees/live-map/",
        EngineerLiveMapAPIView.as_view(),
        name="live-map",
    ),
    path(
        "employees/profile/",
        EmployeeProfileAPIView.as_view(),
        name="employee-profile",
    ),
    path(
        "employees/face-enrollment/",
        FaceEnrollmentAPIView.as_view(),
        name="face-enrollment",
    ),
    path(
        "employees/admin/face-enrollments/",
        AdminFaceEnrollmentListAPIView.as_view(),
        name="admin-face-enrollment-list",
    ),
    path(
        "employees/<int:employee_id>/face-enrollment-control/",
        AdminFaceEnrollmentControlAPIView.as_view(),
        name="admin-face-enrollment-control",
    ),
    path(
        "employees/engineers/",
        EngineerListAPIView.as_view(),
        name="engineer-list",
    ),
    path(
        "employees/assignment-employees/",
        AssignmentEmployeeListAPIView.as_view(),
        name="assignment-employees",
    ),
]
