# Generated by Django 6.0.7 on 2026-08-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('customers', '0003_customer_card_number'),
        ('employees', '0002_employeeprofile_is_online_and_more'),
        ('inventory', '0003_engineerbagitem'),
        ('jobs', '0009_jobsignature'),
        ('partmaster', '0002_partmaster_is_serialized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('service_type', models.CharField(choices=[('REGULAR', 'Regular Service'), ('COMPLAINT', 'Complaint Service'), ('AMC', 'AMC Service'), ('PAID', 'Paid Service')], default='REGULAR', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('input_tds', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tds', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='customers.customer')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='employees.employeeprofile')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service', to='jobs.job')),
                ('ro_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='assets.roasset')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partmaster.partmaster')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='service/photos/')),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before Service'), ('AFTER', 'After Service')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(upload_to='service/signatures/')),
                ('customer_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='service.service')),
            ],
        ),
    ]
