# Generated by Django 6.0.7 on 2026-07-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('capacity', models.CharField(help_text='Example: 12 LPH, 25 LPH, 50 LPH', max_length=50)),
                ('business_type', models.CharField(choices=[('RENT', 'Rental'), ('SALE', 'Sale'), ('AMC', 'AMC')], max_length=10)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='products.productcategory')),
            ],
        ),
    ]
