# Generated by Django 6.0.7 on 2026-07-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partmaster', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partmaster.partmaster')),
                ('ro_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_parts', to='products.romodel')),
            ],
            options={
                'unique_together': {('ro_model', 'part')},
            },
        ),
    ]
