# Generated by Django 6.0.7 on 2026-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partmaster',
            name='is_serialized',
            field=models.BooleanField(default=False, help_text='Enable for parts that require serial number tracking.'),
        ),
    ]
