# Generated by Django 6.0.7 on 2026-08-15 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_customerrentpayment'),
        ('employees', '0002_employeeprofile_is_online_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('complaint_type', models.CharField(choices=[('RO_NOT_WORKING', 'RO Not Working'), ('WATER_LEAKAGE', 'Water Leakage'), ('LOW_TDS', 'Low TDS'), ('BAD_TASTE', 'Bad Taste'), ('LOW_WATER_FLOW', 'Low Water Flow'), ('NO_WATER', 'No Water'), ('PUMP_PROBLEM', 'Pump Problem'), ('MEMBRANE_PROBLEM', 'Membrane Problem'), ('FILTER_PROBLEM', 'Filter Problem'), ('ELECTRICAL', 'Electrical Problem'), ('NOISE', 'Unusual Noise'), ('AMC_SERVICE', 'AMC Service'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=15)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('complaint_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('engineer_remarks', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='customers.customer')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='employees.employeeprofile')),
                ('linked_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='service.service')),
            ],
        ),
    ]
