# Generated by Django 6.0.7 on 2026-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_assigned_engineer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
