# Generated by Django 6.0.7 on 2026-08-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_card_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
