# Generated by Django 6.0.7 on 2026-08-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_old_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_month', models.DateField(blank=True, null=True)),
                ('expected_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('raw_value', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_history', to='customers.customer')),
            ],
            options={
                'ordering': ['rent_month', 'id'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'rent_month'), name='unique_customer_rent_month')],
            },
        ),
    ]
