# Generated by Django 6.0.7 on 2026-08-15 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customerrenthistory'),
        ('employees', '0002_employeeprofile_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_rent_payments', to='employees.employeeprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='customers.customer')),
                ('rent_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customerrenthistory')),
            ],
        ),
    ]
