from io import BytesIO

import openpyxl
from django.http import HttpResponse
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.permissions import IsStaffOperator
from products.models import ROModel
from purchase.models import Purchase, PurchaseItem, Supplier

from .financials import inventory_financial_snapshot
from .models import InventoryAuditLog, InventoryItem, PartRequest
from .reports import _sheet
from .warehouse_security_views import _company_id


def _shop_ro_stock():
    rows = list(
        ROModel.objects.filter(is_active=True)
        .select_related("category")
        .order_by("category__name", "model_name", "id")
    )
    return [
        {
            "id": row.id,
            "category": row.category.name,
            "model_name": row.model_name,
            "capacity": row.capacity,
            "stock_quantity": row.stock_quantity,
            "available_for_sale": row.available_for_sale,
            "available_for_rent": row.available_for_rent,
            "selling_price": row.selling_price,
            "monthly_rent": row.monthly_rent,
        }
        for row in rows
    ]


class ReconciledInventorySummaryAPIView(APIView):
    permission_classes = [IsStaffOperator]

    def get(self, request):
        company_id = _company_id(request)
        snapshot = inventory_financial_snapshot(company_id)
        requests = PartRequest.objects.filter(company_id=company_id)
        shop_ro_stock = _shop_ro_stock()
        return Response({
            "success": True,
            "summary": {
                **snapshot,
                "total_units": snapshot["physical_units"],
                "pending_requests": requests.filter(status="PENDING").count(),
                "approved_requests": requests.filter(status="APPROVED").count(),
                "shop_ro_models": len(shop_ro_stock),
                "shop_ro_units": sum(row["stock_quantity"] for row in shop_ro_stock),
            },
            "shop_ro_stock": shop_ro_stock,
        })


class ReconciledInventoryExcelReportAPIView(APIView):
    permission_classes = [IsStaffOperator]

    def get(self, request):
        company_id = _company_id(request)
        snapshot = inventory_financial_snapshot(company_id)
        workbook = openpyxl.Workbook()
        workbook.remove(workbook.active)

        inventory = InventoryItem.objects.filter(company_id=company_id).select_related(
            "part", "purchase_item__purchase__supplier", "received_by"
        )
        purchases = PurchaseItem.objects.filter(company_id=company_id).select_related(
            "purchase__supplier", "purchase__verified_by", "part"
        )
        requests = PartRequest.objects.filter(company_id=company_id).select_related(
            "engineer__user", "part", "reviewed_by"
        )
        audit = InventoryAuditLog.objects.filter(company_id=company_id).select_related(
            "inventory_item__part", "engineer__user", "performed_by"
        )

        _sheet(workbook, "Executive Summary", ["Metric", "Value"], [
            ("Generated By", request.user.get_full_name() or request.user.phone),
            ("Total Suppliers", Supplier.objects.filter(company_id=company_id).count()),
            ("Total Purchases", Purchase.objects.filter(company_id=company_id).count()),
            ("Purchased Units", snapshot["purchased_units"]),
            ("Physical Inventory Units", snapshot["physical_units"]),
            ("Purchase/Inventory Unit Gap", snapshot["unit_gap"]),
            ("Purchased Value", float(snapshot["purchased_value"])),
            ("Received Units", snapshot["received_units"]),
            ("Received Value", float(snapshot["received_value"])),
            ("Warehouse Units", snapshot["warehouse_units"]),
            ("Stock Value", float(snapshot["warehouse_stock_value"])),
            ("Pending Receipt", snapshot["pending_receipt"]),
            ("In Stock", snapshot["in_stock"]),
            ("Issued", snapshot["issued"]),
            ("Issued Value", float(snapshot["issued_value"])),
            ("Installed", snapshot["installed"]),
            ("Installed Value", float(snapshot["installed_value"])),
            ("Returned", snapshot["returned"]),
            ("Scrap", snapshot["scrap"]),
            ("Scrap Value", float(snapshot["scrap_value"])),
        ])
        _sheet(
            workbook,
            "Stock Ledger",
            ["ID", "Part Code", "Part", "Serial-QR", "Status", "Unit Price", "Invoice", "Supplier"],
            [
                (
                    item.id,
                    item.part.code,
                    item.part.name,
                    item.serial_number or "",
                    item.status,
                    float(item.purchase_item.purchase_price),
                    item.purchase_item.purchase.invoice_number,
                    item.purchase_item.purchase.supplier.name,
                )
                for item in inventory
            ],
        )
        _sheet(
            workbook,
            "Purchases",
            ["Invoice", "Date", "Supplier", "Part Code", "Part", "Quantity", "Unit Price", "Line Total"],
            [
                (
                    item.purchase.invoice_number,
                    item.purchase.invoice_date,
                    item.purchase.supplier.name,
                    item.part.code,
                    item.part.name,
                    item.quantity,
                    float(item.purchase_price),
                    float(item.purchase_price * item.quantity),
                )
                for item in purchases
            ],
        )
        _sheet(workbook, "Part Requests", ["Request", "Employee", "Part", "Qty", "Status"], [
            (row.id, row.engineer.user.get_full_name(), row.part.name, row.quantity, row.status)
            for row in requests
        ])
        _sheet(workbook, "Audit Trail", ["Time", "Action", "Part", "Serial", "Engineer", "Performed By"], [
            (
                row.created_at.replace(tzinfo=None),
                row.action,
                row.inventory_item.part.name,
                row.serial_number,
                row.engineer.user.get_full_name() if row.engineer else "",
                (row.performed_by.get_full_name() or row.performed_by.phone) if row.performed_by else "",
            )
            for row in audit
        ])
        output = BytesIO()
        workbook.save(output)
        response = HttpResponse(
            output.getvalue(),
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        response["Content-Disposition"] = 'attachment; filename="ARI_Professional_Inventory_Report.xlsx"'
        return response
