# Generated by Django 6.0.7 on 2026-07-31 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory', '0002_alter_inventoryitem_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerBagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('INSTALLED', 'Installed'), ('RETURNED', 'Returned')], default='ISSUED', max_length=20)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('install_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_items', to='employees.employeeprofile')),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bag_item', to='inventory.inventoryitem')),
            ],
        ),
    ]
