# Generated by Django 6.0.7 on 2026-09-01 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_partrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryauditlog',
            name='action',
            field=models.CharField(choices=[('ISSUED', 'Issued To Engineer'), ('INSTALLED', 'Installed'), ('RETURNED', 'Returned'), ('SCRAP', 'Marked Scrap'), ('STATUS_CHANGE', 'Status Changed'), ('SECURITY_REJECT', 'Security Rejection'), ('RECEIVED', 'Received Into Stock')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('PENDING_RECEIPT', 'Pending Receipt'), ('IN_STOCK', 'In Stock'), ('ISSUED', 'Issued To Engineer'), ('INSTALLED', 'Installed'), ('RETURNED', 'Returned'), ('SCRAP', 'Scrap')], default='PENDING_RECEIPT', max_length=20),
        ),
        migrations.CreateModel(
            name='PartRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.partrequest')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_request_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
