# Generated by Django 6.0.7 on 2026-08-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("andy", "0003_andyspeechjob"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="andyknowledge",
            new_name="andy_andykn_namespa_a9d660_idx",
            old_name="andy_andykn_namespa_7cb6c4_idx",
        ),
        migrations.RenameIndex(
            model_name="andymemory",
            new_name="andy_andyme_user_id_654833_idx",
            old_name="andy_andymem_user_id_d4580f_idx",
        ),
        migrations.RenameIndex(
            model_name="andypendingaction",
            new_name="andy_andype_user_id_98a09a_idx",
            old_name="andy_andype_user_id_9dbf21_idx",
        ),
    ]
