# Generated by Django 6.0.7 on 2026-07-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('job_type', models.CharField(choices=[('INSTALLATION', 'Installation'), ('SERVICE', 'Service'), ('COMPLAINT', 'Complaint'), ('PAYMENT', 'Payment Collection'), ('REMOVAL', 'Machine Removal')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('ON_ROUTE', 'On Route'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='customers.customer')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='employees.employeeprofile')),
                ('ro_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='assets.roasset')),
            ],
        ),
    ]
