# Generated by Django 6.0.7 on 2026-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_assigned_at_job_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
