# Generated by Django 6.0.7 on 2026-07-30 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('jobs', '0007_jobactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_usage', to='inventory.inventoryitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='jobs.job')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
