# Generated by Django 6.0.7 on 2026-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
