# Generated by Django 6.0.7 on 2026-08-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_customer_otp_job_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
