# Generated by Django 6.0.7 on 2026-07-30 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('partmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('business_type', models.CharField(choices=[('RENT', 'Rental'), ('SALE', 'Sale'), ('AMC', 'AMC')], default='RENT', max_length=10)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='customers.customer')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='employees.employeeprofile')),
                ('ro_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='assets.roasset')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_parts', to='installation.installation')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partmaster.partmaster')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='installation/photos/')),
                ('photo_type', models.CharField(help_text='Front, Side, Customer, Water Source, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='installation.installation')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(upload_to='installation/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='installation.installation')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='installation/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='installation.installation')),
            ],
        ),
    ]
