# Generated by Django 6.0.7 on 2026-07-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
        ('jobs', '0005_jobmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installation', to='jobs.job'),
        ),
    ]
