# Generated by Django 6.0.7 on 2026-07-31 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_installation_job'),
        ('inventory', '0003_engineerbagitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationpart',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
    ]
