# Generated by Django 6.0.7 on 2026-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_installationpart_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='input_tds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='output_tds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='referral_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
