# Generated by Django 6.0.7 on 2026-09-01 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_holiday'),
        ('tenancy', '0005_company_archived_at_company_deletion_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='tenancy.company'),
        ),
    ]
