# Generated by Django 6.0.7 on 2026-09-01 08:00

from django.db import migrations


def assign_existing_employees_to_ari(apps, schema_editor):
    EmployeeProfile = apps.get_model("employees", "EmployeeProfile")
    Company = apps.get_model("tenancy", "Company")
    ari = Company.objects.filter(slug="ari-smart-ro").first()
    if ari:
        EmployeeProfile.objects.filter(company__isnull=True).update(company=ari)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeeprofile_company'),
        ('tenancy', '0005_company_archived_at_company_deletion_scheduled_for_and_more'),
    ]

    operations = [migrations.RunPython(assign_existing_employees_to_ari, migrations.RunPython.noop)]
