from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0027_backfill_corporate_hr_lifecycle"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManpowerRequisition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("department", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=120)),
                ("designation", models.CharField(blank=True, default="", max_length=20)),
                ("positions", models.PositiveSmallIntegerField(default=1)),
                ("employment_type", models.CharField(default="PROBATION", max_length=16)),
                ("location", models.CharField(blank=True, default="", max_length=120)),
                ("target_joining_date", models.DateField(blank=True, null=True)),
                ("justification", models.TextField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PENDING_APPROVAL", "Pending Approval"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("CLOSED", "Closed")], default="DRAFT", max_length=24)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_manpower", to=settings.AUTH_USER_MODEL)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="manpower_requisitions", to="tenancy.company")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requested_manpower", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=160)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("current_company", models.CharField(blank=True, default="", max_length=160)),
                ("current_title", models.CharField(blank=True, default="", max_length=120)),
                ("experience_years", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("source", models.CharField(blank=True, default="", max_length=80)),
                ("resume", models.FileField(blank=True, null=True, upload_to="employees/recruitment/resumes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hr_candidates", to="tenancy.company")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_hr_candidates", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("requirements", models.TextField(blank=True, default="")),
                ("vacancies", models.PositiveSmallIntegerField(default=1)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("OPEN", "Open"), ("ON_HOLD", "On Hold"), ("CLOSED", "Closed"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=16)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="job_openings", to="tenancy.company")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_job_openings", to=settings.AUTH_USER_MODEL)),
                ("requisition", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="job_opening", to="employees.manpowerrequisition")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CandidateApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stage", models.CharField(choices=[("APPLIED", "Applied"), ("SCREENING", "Screening"), ("INTERVIEW", "Interview"), ("SELECTED", "Selected"), ("REJECTED", "Rejected"), ("OFFERED", "Offered"), ("JOINED", "Joined"), ("WITHDRAWN", "Withdrawn")], default="APPLIED", max_length=16)),
                ("expected_salary", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("rejection_reason", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="applications", to="employees.candidate")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="candidate_applications", to="tenancy.company")),
                ("converted_employee", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="source_candidate_application", to="employees.employeeprofile")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_candidate_applications", to=settings.AUTH_USER_MODEL)),
                ("job_opening", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="applications", to="employees.jobopening")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="RecruitmentAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(max_length=40)),
                ("entity_id", models.PositiveBigIntegerField()),
                ("action", models.CharField(max_length=40)),
                ("from_status", models.CharField(blank=True, default="", max_length=40)),
                ("to_status", models.CharField(blank=True, default="", max_length=40)),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recruitment_audit_events", to="tenancy.company")),
                ("performed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recruitment_audit_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="manpowerrequisition", index=models.Index(fields=["company", "status"], name="hr2_req_company_status_idx")),
        migrations.AddIndex(model_name="manpowerrequisition", index=models.Index(fields=["company", "department"], name="hr2_req_company_dept_idx")),
        migrations.AddConstraint(model_name="candidate", constraint=models.UniqueConstraint(fields=("company", "phone"), name="hr2_candidate_company_phone_uniq")),
        migrations.AddIndex(model_name="candidate", index=models.Index(fields=["company", "full_name"], name="hr2_candidate_company_name_idx")),
        migrations.AddIndex(model_name="jobopening", index=models.Index(fields=["company", "status"], name="hr2_job_company_status_idx")),
        migrations.AddConstraint(model_name="candidateapplication", constraint=models.UniqueConstraint(fields=("candidate", "job_opening"), name="hr2_candidate_job_application_uniq")),
        migrations.AddIndex(model_name="candidateapplication", index=models.Index(fields=["company", "stage"], name="hr2_app_company_stage_idx")),
        migrations.AddIndex(model_name="candidateapplication", index=models.Index(fields=["job_opening", "stage"], name="hr2_app_job_stage_idx")),
        migrations.AddIndex(model_name="recruitmentauditevent", index=models.Index(fields=["company", "entity_type", "entity_id"], name="hr2_audit_entity_idx")),
    ]
