from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0028_phase2_recruitment_foundation"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_number", models.PositiveSmallIntegerField()),
                ("round_type", models.CharField(choices=[("HR_SCREENING", "HR Screening"), ("TECHNICAL", "Technical"), ("MANAGERIAL", "Managerial"), ("PRACTICAL", "Practical"), ("FINAL", "Final"), ("OTHER", "Other")], max_length=20)),
                ("scheduled_at", models.DateTimeField()),
                ("location", models.CharField(blank=True, default="", max_length=160)),
                ("meeting_reference", models.CharField(blank=True, default="", max_length=300)),
                ("instructions", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled"), ("NO_SHOW", "No Show")], default="SCHEDULED", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("application", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="interview_rounds", to="employees.candidateapplication")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="interview_rounds", to="tenancy.company")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_interview_rounds", to=settings.AUTH_USER_MODEL)),
                ("interviewer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assigned_interview_rounds", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["scheduled_at", "round_number"]},
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveSmallIntegerField()),
                ("recommendation", models.CharField(choices=[("STRONG_HIRE", "Strong Hire"), ("HIRE", "Hire"), ("HOLD", "Hold"), ("NO_HIRE", "No Hire")], max_length=16)),
                ("strengths", models.TextField(blank=True, default="")),
                ("concerns", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="interview_feedback", to="tenancy.company")),
                ("interview_round", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="feedback_entries", to="employees.interviewround")),
                ("interviewer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="interview_feedback_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.CreateModel(
            name="CandidateOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_title", models.CharField(max_length=120)),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(blank=True, default="", max_length=20)),
                ("employment_type", models.CharField(max_length=16)),
                ("proposed_joining_date", models.DateField()),
                ("work_location", models.CharField(blank=True, default="", max_length=120)),
                ("compensation", models.DecimalField(decimal_places=2, max_digits=12)),
                ("probation_terms", models.CharField(blank=True, default="", max_length=500)),
                ("validity_date", models.DateField()),
                ("hr_notes", models.TextField(blank=True, default="")),
                ("approval_note", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PENDING_APPROVAL", "Pending Approval"), ("APPROVED", "Approved"), ("ISSUED", "Issued"), ("ACCEPTED", "Accepted"), ("DECLINED", "Declined"), ("EXPIRED", "Expired"), ("WITHDRAWN", "Withdrawn")], default="DRAFT", max_length=24)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("response_note", models.TextField(blank=True, default="")),
                ("response_evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("application", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="offer", to="employees.candidateapplication")),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_candidate_offers", to=settings.AUTH_USER_MODEL)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="candidate_offers", to="tenancy.company")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_candidate_offers", to=settings.AUTH_USER_MODEL)),
                ("response_actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="recorded_candidate_offer_responses", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="HrLetter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("letter_type", models.CharField(choices=[("OFFER", "Offer"), ("APPOINTMENT", "Appointment"), ("CONFIRMATION", "Confirmation"), ("PROMOTION", "Promotion"), ("INCREMENT", "Increment"), ("WARNING", "Warning"), ("NOTICE", "Notice"), ("SEPARATION", "Separation")], max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("snapshot", models.JSONField(default=dict)),
                ("content_hash", models.CharField(max_length=64)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("acknowledgement_status", models.CharField(choices=[("PENDING", "Pending"), ("ACKNOWLEDGED", "Acknowledged"), ("DECLINED", "Declined")], default="PENDING", max_length=16)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_offer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="letters", to="employees.candidateoffer")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hr_letters", to="tenancy.company")),
                ("employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="hr_letters", to="employees.employeeprofile")),
                ("issued_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issued_hr_letters", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-issued_at"]},
        ),
        migrations.AddConstraint(model_name="interviewround", constraint=models.UniqueConstraint(fields=("application", "round_number"), name="hr2_interview_application_round_uniq")),
        migrations.AddIndex(model_name="interviewround", index=models.Index(fields=["company", "status", "scheduled_at"], name="hr2_int_company_status_idx")),
        migrations.AddIndex(model_name="interviewround", index=models.Index(fields=["interviewer", "status"], name="hr2_int_interviewer_idx")),
        migrations.AddConstraint(model_name="interviewfeedback", constraint=models.UniqueConstraint(fields=("interview_round", "interviewer"), name="hr2_feedback_round_interviewer_uniq")),
        migrations.AddIndex(model_name="candidateoffer", index=models.Index(fields=["company", "status"], name="hr2_offer_company_status_idx")),
        migrations.AddConstraint(model_name="hrletter", constraint=models.UniqueConstraint(fields=("candidate_offer", "letter_type", "version"), name="hr2_letter_offer_type_version_uniq")),
        migrations.AddIndex(model_name="hrletter", index=models.Index(fields=["company", "letter_type", "issued_at"], name="hr2_letter_company_type_idx")),
    ]
