# Generated by Django 6.0.7 on 2026-09-01 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_supplier_city_supplier_created_at_supplier_pincode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='entry_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('INVOICE_OCR', 'Invoice OCR')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_invoices/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ocr_confidence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
