# Generated by Django 6.0.7 on 2026-09-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_seed_saas_plans_and_ari'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='app_display_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='Public/customer module codes enabled for this tenant.'),
        ),
        migrations.AddField(
            model_name='company',
            name='show_public_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='company',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
